In [1]:
import pandas as pd

In [2]:
# read csv file
df_cars = pd.read_csv('Car_sales.csv')

In [3]:
df_cars

,Manufacturer,Model,Sales_in_thousands,__year_resale_value,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Wheelbase,Width,Length,Curb_weight,Fuel_capacity,Fuel_efficiency,Latest_Launch,Power_perf_factor
0,Acura,Integra,16.919,16.360,Passenger,21.50,1.8,140.0,101.2,67.3,172.4,2.639,13.2,28.0,2/2/2012,58.280150
1,Acura,TL,39.384,19.875,Passenger,28.40,3.2,225.0,108.1,70.3,192.9,3.517,17.2,25.0,6/3/2011,91.370778
2,Acura,CL,14.114,18.225,Passenger,NaN,3.2,225.0,106.9,70.6,192.0,3.470,17.2,26.0,1/4/2012,NaN
3,Acura,RL,8.588,29.725,Passenger,42.00,3.5,210.0,114.6,71.4,196.6,3.850,18.0,22.0,3/10/2011,91.389779
4,Audi,A4,20.397,22.255,Passenger,23.99,1.8,150.0,102.6,68.2,178.0,2.998,16.4,27.0,10/8/2011,62.777639
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
152,Volvo,V40,3.545,NaN,Passenger,24.40,1.9,160.0,100.5,67.6,176.6,3.042,15.8,25.0,9/21/2011,66.498812
153,Volvo,S70,15.245,NaN,Passenger,27.50,2.4,168.0,104.9,69.3,185.9,3.208,17.9,25.0,11/24/2012,70.654495
154,Volvo,V70,17.531,NaN,Passenger,28.80,2.4,168.0,104.9,69.3,186.2,3.259,17.9,25.0,6/25/2011,71.155978
155,Volvo,C70,3.493,NaN,Passenger,45.50,2.3,236.0,104.9,71.5,185.7,3.601,18.5,23.0,4/26/2011,101.623357
156,Volvo,S80,18.969,NaN,Passenger,36.00,2.9,201.0,109.9,72.1,189.8,3.600,21.1,24.0,11/14/2011,85.735655

In [3]:
# selecing columns
df_cars = df_cars[['Manufacturer', 'Sales_in_thousands',
         'Vehicle_type', 'Price_in_thousands',
         'Engine_size', 'Horsepower', 'Fuel_capacity']]

In [5]:
# show dataframe
df_cars

,Manufacturer,Sales_in_thousands,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Fuel_capacity
0,Acura,16.919,Passenger,21.50,1.8,140.0,13.2
1,Acura,39.384,Passenger,28.40,3.2,225.0,17.2
2,Acura,14.114,Passenger,NaN,3.2,225.0,17.2
3,Acura,8.588,Passenger,42.00,3.5,210.0,18.0
4,Audi,20.397,Passenger,23.99,1.8,150.0,16.4
...,...,...,...,...,...,...,...
152,Volvo,3.545,Passenger,24.40,1.9,160.0,15.8
153,Volvo,15.245,Passenger,27.50,2.4,168.0,17.9
154,Volvo,17.531,Passenger,28.80,2.4,168.0,17.9
155,Volvo,3.493,Passenger,45.50,2.3,236.0,18.5
156,Volvo,18.969,Passenger,36.00,2.9,201.0,21.1

In [6]:
# calculate number of unique values
df_cars.nunique()

Manufacturer           30
Sales_in_thousands    157
Vehicle_type            2
Price_in_thousands    152
Engine_size            31
Horsepower             66
Fuel_capacity          55
dtype: int64

# agg()

In [7]:
# calculate the sum of columns
df_cars.agg('sum')

Manufacturer          AcuraAcuraAcuraAcuraAudiAudiAudiBMWBMWBMWBuick...
Sales_in_thousands                                             8320.698
Vehicle_type          PassengerPassengerPassengerPassengerPassengerP...
Price_in_thousands                                             4245.567
Engine_size                                                       477.5
Horsepower                                                      29008.0
Fuel_capacity                                                    2800.5
dtype: object

In [13]:
# calculate the mean of numeric columns
df_cars.mean(numeric_only=True)

Sales_in_thousands     52.998076
Price_in_thousands     27.390755
Engine_size             3.060897
Horsepower            185.948718
Fuel_capacity          17.951923
dtype: float64

In [16]:
# calculate the mean and count values
# df_cars.select_dtypes(include='number').apply(['mean', 'count'])
df_cars.select_dtypes(include='number').agg(['mean', 'sum'])

,Sales_in_thousands,Price_in_thousands,Engine_size,Horsepower,Fuel_capacity
mean,52.998076,27.390755,3.060897,185.948718,17.951923
sum,8320.698000,4245.567000,477.500000,29008.000000,2800.500000

In [19]:
# Different aggregations per column: calculate the sum and mean of 'Sale_in_thousands' and sum and max of 'Price_in_thousands'
df_cars.agg({'Sales_in_thousands':['sum','mean'],
            'Price_in_thousands':['sum','max']})

      Sales_in_thousands  Price_in_thousands
sum          8320.698000            4245.567
mean           52.998076                 NaN
max                  NaN              85.500

In [22]:
# aggregate over the columns
df_cars[['Sales_in_thousands', 'Price_in_thousands']].agg('sum', axis = 1)

0      38.419
1      67.784
2      14.114
3      50.588
4      44.387
        ...
152    27.945
153    42.745
154    46.331
155    48.993
156    54.969
Length: 157, dtype: float64

In [23]:
# equivalent (NaN behaves differently)
df_cars['Sales_in_thousands'] + df_cars['Price_in_thousands']

0      38.419
1      67.784
2         NaN
3      50.588
4      44.387
        ...
152    27.945
153    42.745
154    46.331
155    48.993
156    54.969
Length: 157, dtype: float64

In [26]:
# aggregate different functions and rename the index of the resulting Dataframe
df_cars.agg(x = ('Sales_in_thousands', 'sum'),
            y = ('Price_in_thousands','sum'))

   Sales_in_thousands  Price_in_thousands
x            8320.698                 NaN
y                 NaN            4245.567

# The Split-Apply-Combine Strategy

In [6]:
# split data into separate groups
passenger_filter = df_cars['Vehicle_type'] == 'Passenger'
car_filter = df_cars['Vehicle_type'] == 'Car'

# df_cars['Vehicle_type'].value_counts()

In [10]:
# apply an operation
passenger_avg = df_cars[passenger_filter]['Sales_in_thousands'].mean()
car_avg = df_cars[car_filter]['Sales_in_thousands'].mean()

In [23]:
# combine results
pd.DataFrame({'Vehicle_type':['Car','Passenger'],
             'Sales_in_thousands':[car_avg, passenger_avg]})
# pd.DataFrame({'Vehicle_type':['Car','Passenger'],
#              'Sales_in_thousands':[car_avg, passenger_avg]}).set_index('Vehicle_type')

  Vehicle_type  Sales_in_thousands
0          Car           80.622293
1    Passenger           43.234345

# groupby()

In [21]:
# group by Vehicle_type and calculate the mean
# df_cars.groupby('Vehicle_type').mean(numeric_only=True)
df_cars.groupby('Vehicle_type', as_index=False).mean(numeric_only=True)

,Vehicle_type,Sales_in_thousands,Price_in_thousands,Engine_size,Horsepower,Fuel_capacity
0,Car,80.622293,26.319975,3.520000,186.400000,21.895000
1,Passenger,43.234345,27.763200,2.902586,185.793103,16.592241

In [25]:
# group by Manufacturer
groupby_obj = df_cars.groupby('Manufacturer')

In [30]:
# the groupby_obj
groupby_obj

In [31]:
# groups attribute and keys
groupby_obj.groups.keys()
groupby_obj.groups

{'Acura': [0, 1, 2, 3], 'Audi': [4, 5, 6], 'BMW': [7, 8, 9], 'Buick': [10, 11, 12, 13], 'Cadillac': [14, 15, 16, 17, 18], 'Chevrolet': [19, 20, 21, 22, 23, 24, 25, 26, 27], 'Chrysler': [28, 29, 30, 31, 32, 33, 34], 'Dodge': [35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45], 'Ford': [46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56], 'Honda': [57, 58, 59, 60, 61], 'Hyundai': [62, 63, 64], 'Infiniti': [65], 'Jaguar': [66], 'Jeep': [67, 68, 69], 'Lexus': [70, 71, 72, 73, 74, 75], 'Lincoln': [76, 77, 78], 'Mercedes-B': [92, 93, 94, 95, 96, 97, 98, 99, 100], 'Mercury': [86, 87, 88, 89, 90, 91], 'Mitsubishi': [79, 80, 81, 82, 83, 84, 85], 'Nissan': [101, 102, 103, 104, 105, 106, 107], 'Oldsmobile': [108, 109, 110, 111, 112, 113], 'Plymouth': [114, 115, 116, 117], 'Pontiac': [118, 119, 120, 121, 122, 123], 'Porsche': [124, 125, 126], 'Saab': [127, 128], 'Saturn': [129, 130, 131, 132, 133], 'Subaru': [134, 135], 'Toyota': [136, 137, 138, 139, 140, 141, 142, 143, 144], 'Volkswagen': [145, 146, 147, 148, 149, 150], 'Volvo': [151, 152, 153, 154, 155, 156]}

In [29]:
# get a specific group within the Manufacturer column
groupby_obj.get_group('Ford')

,Manufacturer,Sales_in_thousands,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Fuel_capacity
46,Ford,70.227,Passenger,12.070,2.0,110.0,12.7
47,Ford,113.369,Passenger,21.560,3.8,190.0,15.7
48,Ford,35.068,Passenger,17.035,2.5,170.0,15.0
49,Ford,245.815,Passenger,17.885,3.0,155.0,16.0
50,Ford,175.670,Passenger,12.315,2.0,107.0,13.2
51,Ford,63.403,Passenger,22.195,4.6,200.0,19.0
52,Ford,276.747,Car,31.930,4.0,210.0,21.0
53,Ford,155.787,Car,21.410,3.0,150.0,26.0
54,Ford,125.338,Car,36.135,4.6,240.0,26.0
55,Ford,220.650,Car,12.050,2.5,119.0,20.0
56,Ford,540.561,Car,26.935,4.6,220.0,25.1

In [34]:
# group by Manufacturer and colculate the mean
df_cars.groupby('Manufacturer').mean(numeric_only=True)

,Sales_in_thousands,Price_in_thousands,Engine_size,Horsepower,Fuel_capacity
Manufacturer,,,,,
Acura,19.751250,30.633333,2.925000,200.000000,16.400000
Audi,13.519000,39.980000,2.933333,220.000000,19.533333
BMW,15.501667,33.096667,2.700000,185.333333,17.233333
Buick,60.504750,26.781250,3.625000,206.250000,17.750000
Cadillac,22.435600,40.254000,4.500000,256.000000,20.800000
Chevrolet,61.596111,20.022778,3.055556,171.111111,15.477778
Chrysler,28.817286,23.430833,2.783333,194.833333,16.483333
Dodge,82.740818,24.213636,3.709091,199.545455,21.581818
Ford,183.875909,21.047273,3.327273,170.090909,19.063636
Honda,118.534800,20.277000,2.520000,160.400000,17.080000
Hyundai,45.775333,12.165667,1.966667,126.666667,14.533333
Infiniti,23.713000,29.465000,3.000000,227.000000,18.500000
Jaguar,15.467000,42.800000,3.000000,240.000000,18.400000
Jeep,97.717667,20.991667,3.500000,168.333333,19.833333
Lexus,17.807167,44.055000,3.616667,245.833333,20.533333
Lincoln,28.544667,41.690000,4.866667,263.333333,23.000000
Mercedes-B,13.013889,52.916667,3.422222,232.222222,18.922222
Mercury,39.666500,20.748333,3.150000,163.833333,17.833333
Mitsubishi,25.842143,22.167429,2.800000,165.142857,18.285714
Nissan,57.090714,22.360714,2.914286,169.000000,18.200000
Oldsmobile,29.831500,25.622833,3.450000,190.000000,18.200000
Plymouth,16.000250,22.642500,2.475000,166.750000,15.125000
Pontiac,61.755667,22.949167,3.433333,185.000000,17.916667
Porsche,4.042667,62.473333,3.166667,272.333333,17.000000
Saab,10.653000,29.610000,2.150000,177.500000,17.700000
Saturn,33.770000,14.271000,2.020000,119.600000,12.500000
Subaru,40.067500,21.395000,2.500000,165.000000,16.400000
Toyota,82.245000,21.982889,2.622222,160.666667,17.766667
Volkswagen,34.868667,17.698333,1.966667,120.833333,14.700000
Volvo,12.623333,30.933333,2.300000,182.166667,17.833333

In [36]:
# group by Manufacturer and colculate the sum
df_cars.groupby('Manufacturer').sum(numeric_only=True)

,Sales_in_thousands,Price_in_thousands,Engine_size,Horsepower,Fuel_capacity
Manufacturer,,,,,
Acura,79.005,91.900,11.7,800.0,65.6
Audi,40.557,119.940,8.8,660.0,58.6
BMW,46.505,99.290,8.1,556.0,51.7
Buick,242.019,107.125,14.5,825.0,71.0
Cadillac,112.178,201.270,22.5,1280.0,104.0
Chevrolet,554.365,180.205,27.5,1540.0,139.3
Chrysler,201.721,140.585,16.7,1169.0,98.9
Dodge,910.149,266.350,40.8,2195.0,237.4
Ford,2022.635,231.520,36.6,1871.0,209.7
Honda,592.674,101.385,12.6,802.0,85.4
Hyundai,137.326,36.497,5.9,380.0,43.6
Infiniti,23.713,29.465,3.0,227.0,18.5
Jaguar,15.467,42.800,3.0,240.0,18.4
Jeep,293.153,62.975,10.5,505.0,59.5
Lexus,106.843,264.330,21.7,1475.0,123.2
Lincoln,85.634,125.070,14.6,790.0,69.0
Mercedes-B,117.125,476.250,30.8,2090.0,170.3
Mercury,237.999,124.490,18.9,983.0,107.0
Mitsubishi,180.895,155.172,19.6,1156.0,128.0
Nissan,399.635,156.525,20.4,1183.0,127.4
Oldsmobile,178.989,153.737,20.7,1140.0,109.2
Plymouth,64.001,90.570,9.9,667.0,60.5
Pontiac,370.534,137.695,20.6,1110.0,107.5
Porsche,12.128,187.420,9.5,817.0,51.0
Saab,21.306,59.220,4.3,355.0,35.4
Saturn,168.850,71.355,10.1,598.0,62.5
Subaru,80.135,42.790,5.0,330.0,32.8
Toyota,740.205,197.846,23.6,1446.0,159.9
Volkswagen,209.212,106.190,11.8,725.0,88.2
Volvo,75.740,185.600,13.8,1093.0,107.0

In [38]:
# group by Vehicle_type and count values (NaN values are not counted)
df_cars.groupby('Vehicle_type').count()

,Manufacturer,Sales_in_thousands,Price_in_thousands,Engine_size,Horsepower,Fuel_capacity
Vehicle_type,,,,,,
Car,41,41,40,40,40,40
Passenger,116,116,115,116,116,116

In [39]:
# find null values in columns
df_cars.isnull().sum()

Manufacturer          0
Sales_in_thousands    0
Vehicle_type          0
Price_in_thousands    2
Engine_size           1
Horsepower            1
Fuel_capacity         1
dtype: int64

In [40]:
# group by Engine_size and count values without dropping NaN values
df_cars.groupby('Engine_size', dropna=False).count()

,Manufacturer,Sales_in_thousands,Vehicle_type,Price_in_thousands,Horsepower,Fuel_capacity
Engine_size,,,,,,
1.0,1,1,1,1,1,1
1.5,1,1,1,1,1,1
1.6,1,1,1,1,1,1
1.8,8,8,8,8,8,8
1.9,5,5,5,5,5,5
2.0,17,17,17,17,17,17
2.2,4,4,4,4,4,4
2.3,6,6,6,6,6,6
2.4,11,11,11,11,11,11
2.5,11,11,11,11,11,11
2.7,4,4,4,4,4,4
2.8,3,3,3,3,3,3
2.9,1,1,1,1,1,1
3.0,14,14,14,14,14,14
3.1,4,4,4,4,4,4
3.2,6,6,6,5,6,6
3.3,5,5,5,5,5,5
3.4,7,7,7,7,7,7
3.5,8,8,8,8,8,8
3.8,8,8,8,8,8,8
3.9,2,2,2,2,2,2
4.0,7,7,7,7,7,7
4.2,1,1,1,1,1,1
4.3,2,2,2,2,2,2
4.6,9,9,9,9,9,9
4.7,2,2,2,2,2,2
5.0,2,2,2,2,2,2
5.2,2,2,2,2,2,2
5.4,1,1,1,1,1,1
5.7,2,2,2,2,2,2
8.0,1,1,1,1,1,1
NaN,1,1,1,0,0,0

# Groupby() and agg()

In [43]:
# find the minimum and maximum values on each column
# df_cars.groupby('Vehicle_type').min()
# df_cars.groupby('Vehicle_type').max()

df_cars.groupby('Vehicle_type').agg(['min', 'max'])

             Manufacturer         Sales_in_thousands           \
                      min     max                min      max
Vehicle_type
Car              Cadillac  Toyota              9.126  540.561
Passenger           Acura   Volvo              0.110  247.994

             Price_in_thousands         Engine_size      Horsepower         \
                            min     max         min  max        min    max
Vehicle_type
Car                      11.528  60.105         2.0  5.7      119.0  300.0
Passenger                 9.235  85.500         1.0  8.0       55.0  450.0

             Fuel_capacity
                       min   max
Vehicle_type
Car                   15.1  32.0
Passenger             10.3  23.7

In [44]:
# set a name for aggregated column
# find the min Engine_size and max Horsepower
df_cars.groupby('Vehicle_type').agg(min_engine_size = ('Engine_size', 'min'),
                                   max_horsepower = ('Horsepower', 'max'))

              min_engine_size  max_horsepower
Vehicle_type
Car                       2.0           300.0
Passenger                 1.0           450.0

In [45]:
# group by 'Manufacturer' and calculate the sum of Sales_in_thousands and mean of Price_in_thousands
df_cars.groupby('Manufacturer').agg(sales_sum = ('Sales_in_thousands', 'sum'),
                                   price_mean = ('Price_in_thousands', 'mean'))

              sales_sum  price_mean
Manufacturer
Acura            79.005   30.633333
Audi             40.557   39.980000
BMW              46.505   33.096667
Buick           242.019   26.781250
Cadillac        112.178   40.254000
Chevrolet       554.365   20.022778
Chrysler        201.721   23.430833
Dodge           910.149   24.213636
Ford           2022.635   21.047273
Honda           592.674   20.277000
Hyundai         137.326   12.165667
Infiniti         23.713   29.465000
Jaguar           15.467   42.800000
Jeep            293.153   20.991667
Lexus           106.843   44.055000
Lincoln          85.634   41.690000
Mercedes-B      117.125   52.916667
Mercury         237.999   20.748333
Mitsubishi      180.895   22.167429
Nissan          399.635   22.360714
Oldsmobile      178.989   25.622833
Plymouth         64.001   22.642500
Pontiac         370.534   22.949167
Porsche          12.128   62.473333
Saab             21.306   29.610000
Saturn          168.850   14.271000
Subaru           80.135   21.395000
Toyota          740.205   21.982889
Volkswagen      209.212   17.698333
Volvo            75.740   30.933333

In [50]:
# df_cars.groupby('Manufacturer').sum()['Sales_in_thousands']
df_cars.groupby('Manufacturer')['Price_in_thousands'].mean()

Manufacturer
Acura         30.633333
Audi          39.980000
BMW           33.096667
Buick         26.781250
Cadillac      40.254000
Chevrolet     20.022778
Chrysler      23.430833
Dodge         24.213636
Ford          21.047273
Honda         20.277000
Hyundai       12.165667
Infiniti      29.465000
Jaguar        42.800000
Jeep          20.991667
Lexus         44.055000
Lincoln       41.690000
Mercedes-B    52.916667
Mercury       20.748333
Mitsubishi    22.167429
Nissan        22.360714
Oldsmobile    25.622833
Plymouth      22.642500
Pontiac       22.949167
Porsche       62.473333
Saab          29.610000
Saturn        14.271000
Subaru        21.395000
Toyota        21.982889
Volkswagen    17.698333
Volvo         30.933333
Name: Price_in_thousands, dtype: float64

# Lambda

Apply your own function

In [8]:
# get actual sales and price values
# df_cars.groupby('Manufacturer')[['Sales_in_thousands',
#                                  'Price_in_thousands']].sum().apply(lambda x:x*1000)
df_cars.groupby('Manufacturer').sum().apply(lambda x:x*1000)[['Sales_in_thousands',
                                 'Price_in_thousands']]

              Sales_in_thousands  Price_in_thousands
Manufacturer
Acura                    79005.0             91900.0
Audi                     40557.0            119940.0
BMW                      46505.0             99290.0
Buick                   242019.0            107125.0
Cadillac                112178.0            201270.0
Chevrolet               554365.0            180205.0
Chrysler                201721.0            140585.0
Dodge                   910149.0            266350.0
Ford                   2022635.0            231520.0
Honda                   592674.0            101385.0
Hyundai                 137326.0             36497.0
Infiniti                 23713.0             29465.0
Jaguar                   15467.0             42800.0
Jeep                    293153.0             62975.0
Lexus                   106843.0            264330.0
Lincoln                  85634.0            125070.0
Mercedes-B              117125.0            476250.0
Mercury                 237999.0            124490.0
Mitsubishi              180895.0            155172.0
Nissan                  399635.0            156525.0
Oldsmobile              178989.0            153737.0
Plymouth                 64001.0             90570.0
Pontiac                 370534.0            137695.0
Porsche                  12128.0            187420.0
Saab                     21306.0             59220.0
Saturn                  168850.0             71355.0
Subaru                   80135.0             42790.0
Toyota                  740205.0            197846.0
Volkswagen              209212.0            106190.0
Volvo                    75740.0            185600.0

In [18]:
# subtract values from the mean of each group
# df_cars.groupby('Manufacturer').apply(lambda x:x-x.mean(numeric_only=True), include_groups=False)

#or:
# Separate the numeric columns first, but keep the group column
# numeric_cols = df_cars.select_dtypes(include='number').columns

# Apply the operation only to those numeric columns
# df_cars.groupby('Manufacturer')[numeric_cols].apply(lambda x: x - x.mean())

# modern way:
# 1. Select your numeric columns
numeric_cols = df_cars.select_dtypes(include='number').columns

# 2. Subtract the group mean directly
df_cars[numeric_cols] - df_cars.groupby('Manufacturer')[numeric_cols].transform('mean')

,Sales_in_thousands,Price_in_thousands,Engine_size,Horsepower,Fuel_capacity
0,-2.832250,-9.133333,-1.125000,-60.000000,-3.200000
1,19.632750,-2.233333,0.275000,25.000000,0.800000
2,-5.637250,NaN,0.275000,25.000000,0.800000
3,-11.163250,11.366667,0.575000,10.000000,1.600000
4,6.878000,-15.990000,-1.133333,-70.000000,-3.133333
...,...,...,...,...,...
152,-9.078333,-6.533333,-0.400000,-22.166667,-2.033333
153,2.621667,-3.433333,0.100000,-14.166667,0.066667
154,4.907667,-2.133333,0.100000,-14.166667,0.066667
155,-9.130333,14.566667,0.000000,53.833333,0.666667
156,6.345667,5.066667,0.600000,18.833333,3.266667

# The filter() method

In [6]:
# calculate the mean of Sales_in_thousands
df_cars.mean(numeric_only=True)

Sales_in_thousands     52.998076
Price_in_thousands     27.390755
Engine_size             3.060897
Horsepower            185.948718
Fuel_capacity          17.951923
dtype: float64

In [4]:
df_cars.columns

Index(['Manufacturer', 'Sales_in_thousands', 'Vehicle_type',
       'Price_in_thousands', 'Engine_size', 'Horsepower', 'Fuel_capacity'],
      dtype='object')

In [10]:
 # filter certain values out based on sum() and return a subset
def filter_func(x):
    return x['Sales_in_thousands'].sum() > 52

df_filter = df_cars.groupby(['Manufacturer']).filter(filter_func)
df_filter

,Manufacturer,Sales_in_thousands,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Fuel_capacity
0,Acura,16.919,Passenger,21.500,1.8,140.0,13.2
1,Acura,39.384,Passenger,28.400,3.2,225.0,17.2
2,Acura,14.114,Passenger,NaN,3.2,225.0,17.2
3,Acura,8.588,Passenger,42.000,3.5,210.0,18.0
10,Buick,91.561,Passenger,21.975,3.1,175.0,17.5
...,...,...,...,...,...,...,...
152,Volvo,3.545,Passenger,24.400,1.9,160.0,15.8
153,Volvo,15.245,Passenger,27.500,2.4,168.0,17.9
154,Volvo,17.531,Passenger,28.800,2.4,168.0,17.9
155,Volvo,3.493,Passenger,45.500,2.3,236.0,18.5
156,Volvo,18.969,Passenger,36.000,2.9,201.0,21.1

In [17]:
df_cars.groupby(['Manufacturer']).sum(
    numeric_only = True)['Sales_in_thousands'].sort_values().head(6)

Manufacturer
Porsche     12.128
Jaguar      15.467
Saab        21.306
Infiniti    23.713
Audi        40.557
BMW         46.505
Name: Sales_in_thousands, dtype: float64

In [21]:
df_cars[df_cars['Manufacturer'].isin(['Porsche', 'Jaguar', 'Saab', 'Infiniti', 'Audi', 'BMW'])].shape

(13, 7)

In [24]:
print(df_cars.shape)
print(df_filter.shape)

(157, 7)
(144, 7)